# devtools
spring:
  devtools:
    restart:
      enabled: true

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:~/test;MODE=MYSQL

naver:
  openapi:
    newsUrl: https://openapi.naver.com/v1/search/news.json
    clientId : ENC(hKgIgviTznFXy0nh75mJ/jAyVu6NEmRM7LDOIPg26ZM=)
    clientSecret : ENC(6S0Zw8qzGus4Ffaj2UJJXRKxyb6KYPw/)

koscom:
  stock:
    url : https://sandbox-apigw.koscom.co.kr/v2/market/stocks
    apikey : ENC(am6v4kqS6NCJJpJM30lnn4mRKyu/kmxtm6xvFmJHuj8P8BNM/DZZnfkZw62msZU2)