# devtools
spring:
  devtools:
    restart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

naver:
  openapi:
    newsUrl: https://openapi.naver.com/v1/search/news.json
    clientId : ENC(hKgIgviTznFXy0nh75mJ/jAyVu6NEmRM7LDOIPg26ZM=)
    clientSecret : ENC(6S0Zw8qzGus4Ffaj2UJJXRKxyb6KYPw/)